fix: use 'deno' from path if Deno.execPath() doesn't return a deno ex…
lucacasonato/esbuild_deno_loader pull request #27
Opened 2022-09-28 20:14 UTC by danielr1996

fixes #26 

The solution is pretty simple as it justs assumes that if `Deno.execPath()` doesn't return a path that ends with `deno.exe` (i.e. we assume `deno compile` was used) that we should use `deno` from path. This should work in most cases, but if deno isn't on the path it will also fail, but I'm not aware of a method to find the executable if it's not on path.

2022-10-06 11:34 UTC, ayoreis requested changes
Maybe should save `Deno.execPath()`s result in a variable to avoid calling it twice. I didn't think it's doing very heavy work, but on my test when compiled the first run took 527–3760m, the ones after were faster at 0–1ms.

2022-10-07 11:36 UTC, ayoreis requested changes
I meant to move the variables outside the function, this way `Deno.execPath` is still being called on each call to `info`.

Plus maybe a better way of checking if running inside a compiled executable would be `const isCompiled = dirname(denoExecPath) === Deno.cwd()`, `dirname`'s from std.

2022-10-07 11:37 UTC, ayoreis commented
There is still the problem of what if the runner of the compiled executable doesn't have Deno installed. This should fallback to the portable loader. Maybe like this:

```ts
// mod.ts 

export function denoPlugin(...) {
  let loader = options.loader ?? DEFAULT_LOADER;

  ...

  switch (loader) {
    // deno-lint-ignore no-fallthrough
    case "native": {
      try {
        return nativeLoad(infoCache, url, options);
      } catch (error) {
      if (
        error.name !== "NotFound" &&
        error.message !== "program not found"
      ) {
        throw error;
      }
      
      loader = "portable";
      }
    }
  
    case "portable": {
      return portableLoad(url, options);
    }
  }
}
```

2022-10-09 10:04 UTC, lucacasonato reviewed
I suggest that you force the use `loader: "portable"` instead. I don't like sniffing the `Deno.execPath()`.

2022-10-09 23:27 UTC, danielr1996 commented
Well, there is one thing I totally overlooked which makes my solution completely useless: 
The goal of using `deno compile` is to not require users to install deno in order to run my binary, but falling back to the `deno` executable completely contradicts that goal. So using the portable loader might indeed be the better solution. However, I did a quick test and it didn't work, so I'll have to investigate further, but just a quick question before I try to fix something that can't even work.

The portable loader only supports `data://`, `file://` and `http(s)://` urls right? 

Do relative import's with `file://` work, so can I do import * from `file://../config.ts` or would I need to `import(path.join(Deno.cwd(),'..','config.ts')`. The problem is that the file I'm loading is a config file supplied by the user, like a webpack.config.js, so it would be much nicer to have relative imports out of the box

2022-12-14 01:08 UTC, closed without merging